language: objective-c
osx_image: xcode8.3
xcode_sdk: iphonesimulator10.3
script:
    - xcodebuild test -sdk iphonesimulator10.3 -workspace Gnotes.xcworkspace -scheme Gnotes -destination 'platform=iOS Simulator,name=iPhone 7 Plus,OS=10.3' CODE_SIGNING_REQUIRED=NO