language: objective-c
osx_image: xcode8.3
xcode_sdk: iphonesimulator10.3
script:
    - xcodebuild clean build -sdk iphonesimulator10.3 -project Gnotes.xcodeproj -scheme Gnotes CODE_SIGNING_REQUIRED=NO